name: Publish Package to npmjs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and Build
        run: |
          npm install
          npm run build
      - name: Pushing
        run: |
          npm pkg fix
          cd dist/
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
